---
# tasks file for gocdServer
- name: goCd Repos
  uri:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd-ser.repo

- name: install goCD server
  yum: 
    name: go-server
    state: installed

- name: start goCd Server
  service:
    name: go-server
    state: started
    enabled: true
