---
# tasks file for gocdAgaint.
- name: goCd agent Repos
  uri:
    url: https://download.gocd.org/gocd.repo
    dest: /etc/yum.repos.d/gocd-ag.repo

- name: install goCD agent
  yum: 
    name: go-agent
    state: installed

- name: start goCd agent
  service:
    name: go-agent
    state: started
    enabled: true